#spring:
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 80MB
#
#springdoc:
#  default-produces-media-type: application/json
#
#server:
#  servlet:
#    context-path: /api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/thuto
    username: 'root'
    password: 'Palesa'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 5pFoVEhlK6aTwEit3jKBDyiaSXmaG7U/uPn0f9Xb6//NdLiz34TuoP8iu0XrgxaH
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 9099
  error:
    include-message: always
  servlet:
    context-path: /api/v1

