#spring:
#  profiles:
#    active: dev
#  servlet:
#    multipart:
#      max-file-size: 80mb
#
#springdoc:
#  default-produces-media-type: application/json
#
#server:
#  servlet:
#    context-path: /api/v1

server:
  port: 9099
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: 'root'
    password: 'Palesa'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddt-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect